"""class for testing the register_document method"""
import os
import json
import unittest
from uc3m_consulting import EnterpriseManager
from uc3m_consulting.enterprise_management_exception import EnterpriseManagementException


class TestRegisterDocument(unittest.TestCase):
    """Test cases for register_document - Syntactic Analysis"""

    def setUp(self):
        """Create test environment before each test"""
        self.manager = EnterpriseManager()
        self.test_json_path = "mytest.json"
        self.valid_project_id = "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"
        self.valid_filename = "abcd1234.pdf"

        # Clean up output files before each test
        for f in ["mytest.json", "all_documents.json"]:
            if os.path.exists(f):
                os.remove(f)

        # Register a valid project so PROJECT_ID exists in corporate_operations.json
        if os.path.exists("corporate_operations.json"):
            os.remove("corporate_operations.json")
        self.manager.register_project(
            "A1234567D", "PROJ1", "Valid Project Desc",
            "HR", "01/06/2026", 50000.00
        )
        # Get the real project_id generated by register_project
        with open("corporate_operations.json", "r", encoding="utf-8") as f:
            data = json.load(f)
        self.valid_project_id = data[0]["project_id"]

    def tearDown(self):
        """Clean up files after each test"""
        for f in ["mytest.json", "all_documents.json", "corporate_operations.json"]:
            if os.path.exists(f):
                os.remove(f)

    def write_json(self, content):
        """Helper to write content to test json file"""
        with open(self.test_json_path, "w", encoding="utf-8") as f:
            f.write(content)

    def write_json_dict(self, data: dict):
        """Helper to write a dict to test json file"""
        with open(self.test_json_path, "w", encoding="utf-8") as f:
            json.dump(data, f)

    # ------------------------------------------------------------------
    # TC_M2_01 - VALID full input
    # ------------------------------------------------------------------
    def test_tc_m2_01_valid_full_input(self):
        """TC_M2_01 - Valid PROJECT_ID and FILENAME should return SHA-256 string"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd1234.pdf"
        })
        result = self.manager.register_document(self.test_json_path)
        self.assertIsInstance(result, str)
        self.assertEqual(len(result), 64)

    # ------------------------------------------------------------------
    # TC_M2_02 - Node 1: File not found
    # ------------------------------------------------------------------
    def test_tc_m2_02_file_not_found(self):
        """TC_M2_02 - Non-existent file path should raise exception"""
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document("nonexistent.json")

    # ------------------------------------------------------------------
    # TC_M2_03 - Node 1: File not valid JSON
    # ------------------------------------------------------------------
    def test_tc_m2_03_file_not_valid_json(self):
        """TC_M2_03 - Plain text file should raise exception"""
        self.write_json("this is not json at all")
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_04 - Node 2: Empty JSON object
    # ------------------------------------------------------------------
    def test_tc_m2_04_empty_json_object(self):
        """TC_M2_04 - Empty JSON object should raise exception"""
        self.write_json_dict({})
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_05 - Node 2: Only PROJECT_ID key present
    # ------------------------------------------------------------------
    def test_tc_m2_05_only_project_id_present(self):
        """TC_M2_05 - JSON with only PROJECT_ID and no FILENAME should raise exception"""
        self.write_json_dict({"PROJECT_ID": self.valid_project_id})
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_06 - Node 2: Only FILENAME key present
    # ------------------------------------------------------------------
    def test_tc_m2_06_only_filename_present(self):
        """TC_M2_06 - JSON with only FILENAME and no PROJECT_ID should raise exception"""
        self.write_json_dict({"FILENAME": "abcd1234.pdf"})
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_07 - Node 3: Wrong PROJECT_ID key name
    # ------------------------------------------------------------------
    def test_tc_m2_07_wrong_project_id_key(self):
        """TC_M2_07 - Wrong key name PROJ_ID instead of PROJECT_ID should raise exception"""
        self.write_json_dict({
            "PROJ_ID": self.valid_project_id,
            "FILENAME": "abcd1234.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_08 - Node 4: Wrong FILENAME key name
    # ------------------------------------------------------------------
    def test_tc_m2_08_wrong_filename_key(self):
        """TC_M2_08 - Wrong key name FILE instead of FILENAME should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILE": "abcd1234.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_09 - Node 5: Extra unexpected key
    # ------------------------------------------------------------------
    def test_tc_m2_09_extra_unexpected_key(self):
        """TC_M2_09 - Extra unexpected key in JSON should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "EXTRA_KEY": "somevalue",
            "FILENAME": "abcd1234.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_10 - Node 6: Empty PROJECT_ID value
    # ------------------------------------------------------------------
    def test_tc_m2_10_empty_project_id_value(self):
        """TC_M2_10 - Empty PROJECT_ID value should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": "",
            "FILENAME": "abcd1234.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_11 - Node 7: Extra key alongside FILENAME
    # ------------------------------------------------------------------
    def test_tc_m2_11_extra_key_alongside_filename(self):
        """TC_M2_11 - Extra key alongside FILENAME should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd1234.pdf",
            "EXTRA": "data"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_12 - Node 8: Empty FILENAME value
    # ------------------------------------------------------------------
    def test_tc_m2_12_empty_filename_value(self):
        """TC_M2_12 - Empty FILENAME value should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": ""
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_13 - Node 9: PROJECT_ID 31 chars
    # ------------------------------------------------------------------
    def test_tc_m2_13_project_id_31_chars(self):
        """TC_M2_13 - PROJECT_ID with 31 hex chars should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d",
            "FILENAME": "abcd1234.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_14 - Node 9: PROJECT_ID 33 chars
    # ------------------------------------------------------------------
    def test_tc_m2_14_project_id_33_chars(self):
        """TC_M2_14 - PROJECT_ID with 33 hex chars should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4f",
            "FILENAME": "abcd1234.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_15 - Node 10: FILENAME with no extension
    # ------------------------------------------------------------------
    def test_tc_m2_15_filename_no_extension(self):
        """TC_M2_15 - FILENAME with no extension should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd1234"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_16 - Node 11: PROJECT_ID with non-hex char G
    # ------------------------------------------------------------------
    def test_tc_m2_16_project_id_non_hex_char(self):
        """TC_M2_16 - PROJECT_ID with non-hex character G should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": "G1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4",
            "FILENAME": "abcd1234.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_17 - Node 11: PROJECT_ID with uppercase valid hex
    # ------------------------------------------------------------------
    def test_tc_m2_17_project_id_uppercase_hex_valid(self):
        """TC_M2_17 - PROJECT_ID with uppercase A-F hex chars should be valid"""
        # Register a project and get its ID, then upper case it
        upper_id = self.valid_project_id.upper()
        self.write_json_dict({
            "PROJECT_ID": upper_id,
            "FILENAME": "abcd1234.pdf"
        })
        result = self.manager.register_document(self.test_json_path)
        self.assertEqual(len(result), 64)

    # ------------------------------------------------------------------
    # TC_M2_18 - Node 12: NAME 7 chars
    # ------------------------------------------------------------------
    def test_tc_m2_18_name_7_chars(self):
        """TC_M2_18 - Filename NAME with 7 chars should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd123.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_19 - Node 12: NAME 9 chars
    # ------------------------------------------------------------------
    def test_tc_m2_19_name_9_chars(self):
        """TC_M2_19 - Filename NAME with 9 chars should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd12345.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_20 - Node 13: Valid .docx extension
    # ------------------------------------------------------------------
    def test_tc_m2_20_valid_docx_extension(self):
        """TC_M2_20 - Valid .docx extension should return SHA-256 string"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd1234.docx"
        })
        result = self.manager.register_document(self.test_json_path)
        self.assertEqual(len(result), 64)

    # ------------------------------------------------------------------
    # TC_M2_21 - Node 13: Valid .xlsx extension
    # ------------------------------------------------------------------
    def test_tc_m2_21_valid_xlsx_extension(self):
        """TC_M2_21 - Valid .xlsx extension should return SHA-256 string"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd1234.xlsx"
        })
        result = self.manager.register_document(self.test_json_path)
        self.assertEqual(len(result), 64)

    # ------------------------------------------------------------------
    # TC_M2_22 - Node 13: Invalid .txt extension
    # ------------------------------------------------------------------
    def test_tc_m2_22_invalid_txt_extension(self):
        """TC_M2_22 - Invalid .txt extension should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd1234.txt"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_23 - Node 13: Invalid .pptx extension
    # ------------------------------------------------------------------
    def test_tc_m2_23_invalid_pptx_extension(self):
        """TC_M2_23 - Invalid .pptx extension should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd1234.pptx"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_24 - Node 14: Special char in PROJECT_ID
    # ------------------------------------------------------------------
    def test_tc_m2_24_special_char_in_project_id(self):
        """TC_M2_24 - PROJECT_ID with special character should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3!4",
            "FILENAME": "abcd1234.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_25 - Node 15: Underscore in NAME
    # ------------------------------------------------------------------
    def test_tc_m2_25_underscore_in_name(self):
        """TC_M2_25 - Underscore in filename NAME should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd_123.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_26 - Node 15: Hyphen in NAME
    # ------------------------------------------------------------------
    def test_tc_m2_26_hyphen_in_name(self):
        """TC_M2_26 - Hyphen in filename NAME should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd-123.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_27 - Node 16: Uppercase extension .PDF
    # ------------------------------------------------------------------
    def test_tc_m2_27_uppercase_extension(self):
        """TC_M2_27 - Uppercase extension .PDF should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd1234.PDF"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_28 - Node 17: NAME with all uppercase letters
    # ------------------------------------------------------------------
    def test_tc_m2_28_name_all_uppercase(self):
        """TC_M2_28 - NAME with all uppercase letters should be valid"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "ABCD1234.pdf"
        })
        result = self.manager.register_document(self.test_json_path)
        self.assertEqual(len(result), 64)

    # ------------------------------------------------------------------
    # TC_M2_29 - Node 17: NAME with all digits
    # ------------------------------------------------------------------
    def test_tc_m2_29_name_all_digits(self):
        """TC_M2_29 - NAME with all digits should be valid"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "12345678.pdf"
        })
        result = self.manager.register_document(self.test_json_path)
        self.assertEqual(len(result), 64)

    # ------------------------------------------------------------------
    # TC_M2_30 - Node 15: Space in NAME
    # ------------------------------------------------------------------
    def test_tc_m2_30_space_in_name(self):
        """TC_M2_30 - Space in filename NAME should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": self.valid_project_id,
            "FILENAME": "abcd 123.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)

    # ------------------------------------------------------------------
    # TC_M2_31 - Node 6: Valid format PROJECT_ID not in corporate_operations.json
    # ------------------------------------------------------------------
    def test_tc_m2_31_project_id_not_registered(self):
        """TC_M2_31 - Valid format PROJECT_ID not in corporate_operations.json should raise exception"""
        self.write_json_dict({
            "PROJECT_ID": "ffffffffffffffffffffffffffffffff",
            "FILENAME": "abcd1234.pdf"
        })
        with self.assertRaises(EnterpriseManagementException):
            self.manager.register_document(self.test_json_path)


if __name__ == '__main__':
    unittest.main()